apiVersion: v1
kind: Pod
metadata:
    labels:
        app: greeting-app
        version: latest
    name: greeting-app
spec:
    containers:
        - name: greeting-app
          image: spaceuptech/greeter:latest
          ports:
              - containerPort: 8080
          resources:
              requests:
                  memory: '64Mi'
                  cpu: '250m'
              limits:
                  memory: '128Mi'
                  cpu: '500m'
          livenessProbe:
              httpGet:
                  path: /greeting/john
                  port: 8080
              initialDelaySeconds: 3
              periodSeconds: 3
