apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: greeting-app
        version: latest
    name: greeting-app-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            app: greeting-app
            version: latest
    template:
        metadata:
            labels:
                app: greeting-app
                version: latest
        spec:
            containers:
                - name: greeting-app
                  image: spaceuptech/greeter:latest
                  ports:
                      - containerPort: 8080
                  resources:
                      requests:
                          memory: '64Mi'
                          cpu: '250m'
                      limits:
                          memory: '128Mi'
                          cpu: '500m'
                  livenessProbe:
                      httpGet:
                          path: /greeting/john
                          port: 8080
                      initialDelaySeconds: 3
                      periodSeconds: 3
