apiVersion: v1
kind: Service
metadata:
    creationTimestamp: null
    labels:
        app: greeting-app-service
    name: greeting-app-service
spec:
    ports:
        - name: http
          port: 8080
          protocol: TCP
          targetPort: 8080
    selector:
        app: greeting-app
        version: latest
    type: ClusterIP
status:
    loadBalancer: {}
